[tool.poetry]
name = "notice"
version = "0.1.0"
description = ""
authors = ["Aliaksandr Shyrokau <a.shyrokau@godeltech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
