apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-scan-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-scan-identity
  template:
    metadata:
      labels:
        app: sync-scan-identity
    spec:
      containers:
      - name: sync-scan-identity-container
        image: levigoldman/sync-scan-identity
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          protocol: TCP
